version: '3.8'

services:
  todoapi_postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: todoapi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - todoapi_postgres_data:/var/lib/postgresql/data

  todoapi:
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_HOST: jdbc:postgresql://todoapi_postgres:5432/todoapi
      DB_USERNAME: postgres
      DB_PASSWORD: ${DB_PASSWORD}
      SECURITY_SECRET: ${SECURITY_SECRET}

volumes:
  todoapi_postgres_data:
    driver: local
