server:
  port: 8080

spring:
  datasource:
    url: "${DB_HOST}"
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    path: "/api-docs"
  swagger-ui:
    path: "/swagger-ui"

app:
  tokenSecret: ${SECURITY_SECRET}
  tokenIssuer: slamach
  tokenExpirationMSec: 864000000
